apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-env
  namespace: flux-system
data:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://host.docker.internal:4566
