apiVersion: v1
kind: Service
metadata:
  name: localstack-nodeport
  namespace: localstack
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: localstack
  ports:
    - port: 4566
      targetPort: 4566
      nodePort: 30066